#---- Environment Varibales -------------------------------#

env = XCURSOR_SIZE,                       24
env = HYPRCURSOR_SIZE,                    24
env = XCURSOR_THEME,                      Bibata-Modern-Ice
env = HYPRCURSOR_THEME,                   Bibata-Modern-Ice
env = QT_QPA_PLATFORM,                    wayland
env = QT_QPA_PLATFORMTHEME,               qt6ct
env = QT_WAYLAND_DISABLE_WINDOWDECORATION,1
env = QT_AUTO_SCREEN_SCALE_FACTOR,        1
env = ELECTRON_OZONE_PLATFORM_HINT,       wayland
